KVM 2021 Talk
sdlab-naist/website pull request #111
Opened 2021-09-30 08:00 UTC by gqlo

KVM 2021 Talk

2021-09-30 12:17 UTC, keichi requested changes
Please create your post under `content/en` instead of `content/ja`. I will add a Japanese translation afterward.

2021-09-30 12:17 UTC, keichi commented on content/ja/post/li-kvm-forum-21/index.md
> +title: "Mr. Guoqing Li and Dr.Dario Faggioli's Collabrative Talk at KVM FORUM 2021"
Need a space after Dr.

2021-09-30 12:17 UTC, keichi commented on content/ja/post/li-kvm-forum-21/index.md
> +tags: ["Cloud Computing", "Virtualization Performance", "KubeVirt", "Kubernetes"]
Please change `"Cloud Computing"` to `"Cloud"`. This way the post will be linked from this page:
https://sdlab.naist.jp/tags/cloud/

2021-09-30 12:17 UTC, keichi commented on content/ja/post/li-kvm-forum-21/index.md
> +Mr.Guoqing Li, a master student from SDLab and Dr.Dario Faggioli, a virtualization specialist from SUSE lab gave a joint [talk](https://youtu.be/x_czS9Iuo2o) on the topic of KubeVirt: The cost of Con
Need a space after Mr. and Dr.

2021-09-30 12:17 UTC, keichi commented on content/ja/post/li-kvm-forum-21/index.md
> +The introduction and presentation slides of the talk is available at [here](https://events.linuxfoundation.org/kvm-forum/program/schedule/).
https://sched.co/ke2r would be better as it is a direct link to your talk.

2021-10-01 02:53 UTC, keichi commented
Hugo build is failing -- please move your post under `content/en/post/` and add a _relative_ symlink.

2021-10-01 04:06 UTC, gqlo commented
> Hugo build is failing -- please move your post under `content/en/post/` and add a _relative_ symlink.

Interesting. i had to copy the folders to another location, then I can create a relative symlink, otherwise it's created as a file not a folder.

2021-10-02 06:09 UTC, keichi commented
FYI this is the correct way to do it:
```
cd content/en/post
ln -s ../../ja/post/li-kvm-forum-21 li-kvm-forum-21
```

2021-10-02 06:09 UTC, keichi approved these changes

2021-10-02 06:09 UTC, merged