Profile of gaoshan
sdlab-naist/website pull request #123
Opened 2022-04-14 09:59 UTC by MGMCN

Add Profile of gaoshan.

2022-04-14 10:17 UTC, KoheiIchikawa requested changes
content/en/authors/gaoshan/avatar.jpg は削除してください。
日本語ページにjpgがある場合は、それが再利用されます。

2022-04-14 11:01 UTC, MGMCN commented
The avatar.jpg has been deleted

2022-04-14 13:49 UTC, KoheiIchikawa requested changes
最初にちゃんと調べておくべきでしたが、このavatar画像は著作権で保護されているアニメのキャラクターですね。この画像を大学のページに掲載することはできないので、別の写真か自身が著作権を持っているイラストもしくは使用許諾のある画像に変更してください。

2022-04-15 00:56 UTC, MGMCN commented
申し訳ありませんが、日本の著作権政策を知りません。これはイタリアで食べたイカ汁麺です。😂

2022-04-15 03:50 UTC, KoheiIchikawa approved these changes

2022-04-15 03:50 UTC, merged