comments
sdlab-naist/website pull request #147
Opened 2022-12-08 10:05 UTC by WEI44ZHEYUAN

2022-12-08 10:08 UTC, WEI44ZHEYUAN reviewed
comment

2022-12-08 12:15 UTC, KoheiIchikawa requested changes

2022-12-08 12:24 UTC, WEI44ZHEYUAN commented on content/ja/authors/zheyuan-wei/_index.md
> +  - course:  機械工学(未完成)
because I change Major before

2022-12-09 05:55 UTC, KoheiIchikawa approved these changes

2022-12-09 05:55 UTC, merged