move the previous m2 to alumni
sdlab-naist/website pull request #162
Opened 2023-04-26 09:45 UTC by Yutaro-Kashiwa

2023-04-26 15:46 UTC, KoheiIchikawa requested changes
すみません。指摘漏れていたのですが、weightを卒業年月に変更する必要がありました。卒業生を卒業時期でソートさせるために。すみませんが、対応お願い致します。

2023-04-27 03:36 UTC, Yutaro-Kashiwa commented
レビューありがとうございます．Weightを202303に変更しました

2023-04-28 02:37 UTC, keichi commented
`.DS_Store` がコミットされているので削除した方がいいかもしれません

2023-04-28 15:56 UTC, KoheiIchikawa requested changes
.DS_Storeが確かにありますね。新M1でも入れてしまってる学生がいましたね。
.gitignoreにそもそも追加すべき？

2023-04-29 07:21 UTC, keichi commented
個人的にはプロジェクトに関わらず共通のものは `~/.gitignore_global` に書いていますが，ミスを予防するには `.gitignore` に書いてしまうのが良さそうですね．

2023-05-03 07:19 UTC, KoheiIchikawa commented
まだ.DS_Storeが取り切れていない気がする

2023-05-05 11:15 UTC, Yutaro-Kashiwa commented
ようやく全部消せました．．．たぶん

2023-05-05 12:10 UTC, KoheiIchikawa commented
あれ、なんか高専生の post/kosens-sigss2023 の記事がまぎれ混んできている。
post/kosens-sigss2023 は既にmasterにマージ済みのコンテンツなので、conflict 起こしてます。
削除して再Pushお願いします。

2023-05-05 12:17 UTC, Yutaro-Kashiwa commented
すいません，削除しました．なんで紛れ込んでたんでしょう

2023-05-05 12:22 UTC, KoheiIchikawa approved these changes

2023-05-05 12:23 UTC, merged

2023-05-05 12:25 UTC, KoheiIchikawa commented
なんかマージコミットの履歴があるので、マージ元から紛れ込んできたのでは？
Merge branch 'master2022left' of https://github.com/sdlab-naist/website…