Access page
sdlab-naist/website pull request #166
Opened 2023-05-03 03:37 UTC by Yutaro-Kashiwa

2023-05-03 07:12 UTC, KoheiIchikawa commented
現状、HomeページとAbout usにも情報が分散しているので整理したほうがよさそうですよね？
Access関係はこの追加ページにまとめてくれたので、Aboutからアクセスとお問い合わせを削除
Homeページからも地図は削除。連絡先は一応残す？

2023-05-05 11:18 UTC, Yutaro-Kashiwa commented
私も，作成している際にそうしてみたのですが，かなりページが寂しくなるので，一旦このままにしています．
後にAbout usをリファクタリングしようと思うのですが，その際に連絡先は削除しようと思います．
HOMEについては，要議論ですね

2023-05-05 12:13 UTC, KoheiIchikawa requested changes

2023-05-05 12:13 UTC, KoheiIchikawa commented on content/ja/access/access2lab.md
> +**ソフトウェア設計学研究室は，先端科学技術研究科 情報科学領域 A棟3階にあります．
本文は太字にする必要ないと思います。

2023-05-05 12:13 UTC, KoheiIchikawa commented on content/ja/access/access2university.md
> +**NAISTの最寄駅は「学研北生駒駅」となります．駅からNAISTまでは徒歩20分程度必要です．数は多いとは言えませんが，「学研北生駒駅」，「学園前駅」，「学研奈良登美ヶ丘駅」からバスが出ています．詳細は[NAIST公式ページ](http://www.naist.jp/accessmap/)をご覧ください．**
こちらも太字の解除お願いします。

2023-05-05 12:30 UTC, Yutaro-Kashiwa commented
太字をやめてみました．最初は太字にしてなかったのですが，セクションがなくバランスが悪かったので太字にしてました．もし問題なければ，マージお願いします．

2023-05-05 13:04 UTC, KoheiIchikawa approved these changes

2023-05-05 13:04 UTC, merged