katoadd
sdlab-naist/website pull request #201
Opened 2024-04-22 13:01 UTC by kr37577

2024-04-22 13:03 UTC, Yutaro-Kashiwa requested changes
- ディレクトリ名は自分の名前になるようにしてほしい
riku-kato

_index.mdのauthorsも同様に

2024-04-22 13:35 UTC, Yutaro-Kashiwa requested changes

2024-04-22 13:35 UTC, Yutaro-Kashiwa commented on content/en/authors/riku-kato/riku-kato.jpg
英語版には写真ファイルはいらない

2024-04-22 13:35 UTC, kr37577 commented on content/en/authors/riku-kato/riku-kato.jpg
わかりました

2024-04-23 06:14 UTC, Yutaro-Kashiwa requested changes

2024-04-23 06:14 UTC, Yutaro-Kashiwa commented on content/en/authors/riku-kato/_index.md
> +- "Riku-Kato"
ディレクトリと合わせて
riku-kato
にしてほしい

2024-04-23 06:14 UTC, Yutaro-Kashiwa commented on content/en/authors/riku-kato/_index.md
> +- icon: twitter
使っていないのはコメントアウトしよう（メール以外）
コメントアウトここから

2024-04-23 06:14 UTC, Yutaro-Kashiwa commented on content/en/authors/riku-kato/_index.md
> +  link: https://github.com/USERNAME
ここまで

2024-04-23 06:14 UTC, Yutaro-Kashiwa commented on content/ja/authors/riku-kato/_index.md
> +- "加藤-陸"
ruku-kato
にする．
これが加藤くんのユーザーネームなので

2024-04-23 06:14 UTC, Yutaro-Kashiwa commented on content/ja/authors/riku-kato/_index.md
> +- icon: twitter
英語版と同様にコメントアウト．

2024-04-23 07:56 UTC, kr37577 commented on content/ja/authors/riku-kato/_index.md
> +- icon: twitter
すいませんでした
修正しました

2024-04-23 11:17 UTC, Yutaro-Kashiwa approved these changes

2024-04-23 11:17 UTC, merged