模様替えしてみた
sdlab-naist/website pull request #202
Opened 2024-05-02 06:52 UTC by Yutaro-Kashiwa

2024-05-02 08:29 UTC, KoheiIchikawa requested changes
背景上のテキストが少し読みづらい気がするので改善案をコードにコメント入れました。
あと英語版のsliderも同様に編集が必要です。

2024-05-02 08:29 UTC, KoheiIchikawa commented on content/ja/home/slider.md
> +  title = "<font style='color: darkblue'>ソフトウェア設計学研究室</font>"
テキストと背景の区別をよりつけるためにテキストに白い影をつけてはどうかな？
`text-shadow: 0 0 3px white;`をfontのstyleに追加

2024-05-02 08:29 UTC, KoheiIchikawa commented on content/ja/home/slider.md
> +  title = "<font style='color: white;font-style: italic;font-family: Georgia, serif;'>デザインセンスの工学的追求</font>"
こちらには黒い影
`text-shadow: 0 0 3px black;`

2024-05-02 08:33 UTC, KoheiIchikawa commented
あと画像サイズが大きすぎるかも。
縦を300pxで表示するなら元画像も縦300pxに圧縮しておくべき。

2024-05-02 08:40 UTC, KoheiIchikawa commented
画像はブラウザウィンドウの横幅に応じて、伸縮するようですね。
なので、トリミングする際には単純に縦300pxでトリミングすれば良いのかは不明です。
いくつか典型的なウィンドウのサイズで確認して見栄えのよいトリミング位置を見つける必要がありそうです。

2024-05-02 08:58 UTC, Yutaro-Kashiwa commented
いい感じになりました．画像のサイズと，英語版の2ページ目は一旦見送りでお願いします．

2024-05-02 09:45 UTC, KoheiIchikawa requested changes

2024-05-02 09:45 UTC, KoheiIchikawa commented on content/ja/home/.slider.md.swp
viのスワップファイルが紛れているようです。削除お願いします。

2024-05-02 11:33 UTC, Yutaro-Kashiwa commented
レビューありがとうございます．不要なファイルと写真を微調整しました．ご確認お願いします

2024-05-03 10:33 UTC, KoheiIchikawa commented
クロップした後に画像の圧縮レベルが元に戻ったのか、またサイズが2MBくらいになっている。
いっそのことwebp形式にしてしまう？かなり軽くなると思う。

2024-05-03 13:40 UTC, Yutaro-Kashiwa commented
@KoheiIchikawa 不思議ですね．修正しました．ご確認のほどお願い致します．

2024-05-03 14:55 UTC, KoheiIchikawa approved these changes

2024-05-03 14:55 UTC, merged