森川のICSME記事作成
sdlab-naist/website pull request #223
Opened 2024-11-05 05:25 UTC by yattinda

## 概要
ICSME記事作成（日本語＆英語）
## 要対応
論文へのアクセスリンクの追加

2024-11-18 08:39 UTC, Yutaro-Kashiwa commented
タイトルがSCAMになってる

2024-11-18 08:40 UTC, Yutaro-Kashiwa commented
あとはOK．とりあえず投稿して，あとから修正スタイルで

2024-11-19 02:42 UTC, Yutaro-Kashiwa requested changes

2024-11-19 02:42 UTC, Yutaro-Kashiwa commented on content/ja/post/morikawa_ICSME24/index.md
> +title: "森川君がSCAM2024で発表しました"
ここをICSMEにして

2024-11-19 02:50 UTC, yattinda commented on content/ja/post/morikawa_ICSME24/index.md
> +title: "森川君がSCAM2024で発表しました"
すみません今反映させました

2024-11-19 03:35 UTC, Yutaro-Kashiwa commented
ありがとう！マージします

2024-11-19 03:35 UTC, Yutaro-Kashiwa approved these changes

2024-11-19 03:36 UTC, merged