AXIES2020 Microsoftセッションの記事を追加
sdlab-naist/website pull request #73
Opened 2020-12-09 07:23 UTC by keichi

2020-12-09 07:41 UTC, KoheiIchikawa requested changes

2020-12-09 07:41 UTC, KoheiIchikawa commented on content/ja/post/axies2020-microsoft-session/index.md
> +当該セッションでは，「Microsoft Azureで実現する、 大学計算機センターで最新GPUを提供し続けるハイブリッドHPCクラウドとは 」
大学計算機センターの直前に"Line Separator"が入っているみたいで，Chromeで見ると"L SEP"という謎の文字が見える．

2020-12-09 08:45 UTC, keichi commented
ありがとうございます，修正しました．ときどきSpeakerDeckがカラムからはみ出すのですが私だけですかね?

2020-12-09 23:57 UTC, KoheiIchikawa commented
こちらでも最初のアクセス（キャッシュ無し）の場合だと正常なんですが，再読み込みするとはみ出ますね．
何ででしょう？
ちょっと調べても不明そうでしたら，このままマージしますが．

2020-12-12 00:35 UTC, KoheiIchikawa commented
これ結局原因不明ですね。
SpeakerDeckの埋め込みコードのバグなんでしょうか？親ノードの幅を基準にスライドのサイズを自動生成しているようなんですが、親ノードのサイズの認識を間違うことがあるようです。そのうちSpeakerDeck側が修正するだろうと信じて、とりあえずマージしておきますね。

2020-12-12 00:35 UTC, KoheiIchikawa approved these changes

2020-12-12 00:36 UTC, merged

2020-12-14 02:44 UTC, keichi commented
ありがとうございます．下記のようなエラーが出ているので，クロスドメイン制約絡みっぽい? 気がします．

```
Uncaught DOMException: Blocked a frame with origin "https://speakerdeck.com" from accessing a cross-origin frame.
    at e.value (https://d1eu30co0ohy4w.cloudfront.net/assets/player-e84810d937179934c0d0.js:1:4710)
    at new e (https://d1eu30co0ohy4w.cloudfront.net/assets/player-e84810d937179934c0d0.js:1:3565)
    at Function.c.init (https://d1eu30co0ohy4w.cloudfront.net/assets/player-e84810d937179934c0d0.js:1:12891)
    at HTMLDocument.<anonymous> (https://d1eu30co0ohy4w.cloudfront.net/assets/player-e84810d937179934c0d0.js:1:2400)
```