Add a blog post about spring 2021 graduation.
sdlab-naist/website pull request #85
Opened 2021-03-23 08:57 UTC by boom10899

Could you please review the blog post in Japanese version?

I'm also not sure the type of master's degree that they received (engineering or science). Could you please add or modify it? Thank you very much.

2021-03-23 09:06 UTC, keichi requested changes

2021-03-23 09:06 UTC, keichi commented on content/en/post/spring2021-graduation/index.md
> +authors: []
Put your user name (`"wassapon-watanakeesuntorn"`) here

2021-03-23 09:06 UTC, keichi commented on content/en/post/spring2021-graduation/index.md
> +title: "Spring 2021 Graduation"
Spring 2021 Graduation Ceremony

2021-03-23 09:06 UTC, keichi commented on content/en/post/spring2021-graduation/index.md
> +lastmod: 2021-03-23T17:19:14+09:00
Change these dates to 3/25 since they are officially receiving their degrees tomorrow.

2021-03-23 09:06 UTC, keichi commented on content/ja/post/spring2021-graduation/index.md
> +lastmod: 2021-03-23T17:14:10+09:00
Same as English

2021-03-23 09:06 UTC, keichi commented on content/ja/post/spring2021-graduation/index.md
> +authors: []
Same as English

2021-03-23 09:06 UTC, keichi commented on content/ja/post/spring2021-graduation/index.md
> +title: "春２０２１の学位記授与式"
Change to 令和2年度学位記授与式

2021-03-23 09:06 UTC, keichi commented
The name of their degree is correct.

2021-03-23 09:12 UTC, keichi commented
Btw are you going to add the group photo to the gallery page in another pull request?

2021-03-25 04:33 UTC, keichi approved these changes
Thanks!

2021-03-25 04:33 UTC, merged

2021-03-25 04:34 UTC, boom10899 commented
Thank you very much. I'll do another pull request for lab photos in gallery.