メンバーの追加（福本）
sdlab-naist/website pull request #89
Opened 2021-04-14 04:05 UTC by KACG-D

メンバーを追加しました．

2021-04-14 05:47 UTC, chez-shanpu approved these changes
LGTM 👍

2021-04-14 05:53 UTC, keichi requested changes
- `content/en/authors/daisuke-fukumoto/avatar.jpg`は削除してください．デフォルトで日本語版の画像が使われます．
- 同じメッセージのコミットが複数あるので，1つにまとめて (squash) ください．

2021-04-14 05:53 UTC, keichi commented on content/en/authors/daisuke-fukumoto/_index.md
> +weight: 202004
```suggestion
weight: 202104
```

2021-04-14 05:53 UTC, keichi commented on content/ja/authors/daisuke-fukumoto/_index.md
> +weight: 202004
```suggestion
weight: 202104
```

2021-04-14 07:50 UTC, keichi approved these changes
ありがとう :+1:

2021-04-14 11:36 UTC, chez-shanpu approved these changes
LGTM 👍

2021-04-14 11:36 UTC, merged

2021-04-15 08:23 UTC, KoheiIchikawa commented
@KACG-D
英語ページの名前標記が日本語になってます。急ぎではないですが、修正してください。