Create my webpage
sdlab-naist/website pull request #96
Opened 2021-05-12 05:24 UTC by toshiki-h

I created my own page on the website. Could one of us review my pullrequest?

2021-05-12 06:42 UTC, keichi requested changes
細かいことばかりですみませんが，ご対応お願いします．

あと`content/en/authors/toshiki-hirao/avatar.jpg` は削除してください．デフォルトで日本語版の画像が使用されます．

2021-05-12 06:42 UTC, keichi commented on content/ja/authors/toshiki-hirao/_index.md
> +  link: #https://github.com/USERNAME
リンクが切れているので，URLを入れるか削除してもらえますか? ここにある以外のアイコンを追加することも可能です．

2021-05-12 06:42 UTC, keichi commented on content/en/authors/toshiki-hirao/_index.md
> +- Group 2
```suggestion
- Staff
```

2021-05-12 06:42 UTC, keichi commented on content/en/authors/toshiki-hirao/_index.md
> +- Group 2
これがないとメンバ一覧ページに表示されないので

2021-05-12 06:42 UTC, keichi commented on content/en/authors/toshiki-hirao/_index.md
> +#   link: files/cv.pdf
日本語版と同様，リンクが切れているのでURLを修正するか削除してください．

2021-05-12 06:42 UTC, keichi commented on content/en/authors/toshiki-hirao/_index.md
> +  url: ""
記入してください．

2021-05-12 06:42 UTC, keichi commented on content/en/authors/toshiki-hirao/_index.md
> +    year: 2012
日本語版と同様にプロフィールを記入するか，削除してください．

2021-05-12 06:42 UTC, keichi commented on content/en/authors/toshiki-hirao/_index.md
> +role:
記入してください．

2021-05-12 12:10 UTC, toshiki-h commented on content/ja/authors/toshiki-hirao/_index.md
> +  link: #https://github.com/USERNAME
細部までご確認いただき、誠にありがとうございます！お手数おかけしました。少々時間かかりますが、１つずつ対応していきます。

2021-07-26 08:39 UTC, keichi commented
@toshiki-h すみませんが，お時間ある時にこちらの対応お願いします

2021-07-27 03:41 UTC, dtosh-master commented
@keichi こちら対応遅くなり、申し訳ございませんでした。7月中に修正しますので、何卒宜しくお願い致します。

2021-07-27 03:43 UTC, toshiki-h commented
@keichi こちら対応遅くなり、申し訳ございませんでした。7月中に修正しますので、何卒宜しくお願い致します。

(先程は違うアカウントで誤返信してしまいました。すみませんでした。)

2021-07-31 11:16 UTC, toshiki-h commented
@keichi すみません、今週かなり立て込んでまして、来週のどこかで仕上げます。

2021-07-31 11:18 UTC, keichi commented
了解です，急ぎではないですが忘れないようリマインドしただけです．

2021-08-08 01:41 UTC, toshiki-h commented on content/en/authors/toshiki-hirao/_index.md
> +#   link: files/cv.pdf
メールアドレス、及びtwitterのみ記載しました。

2021-08-08 01:41 UTC, toshiki-h commented on content/en/authors/toshiki-hirao/_index.md
> +- Group 2
DONE

2021-08-08 01:41 UTC, toshiki-h commented on content/ja/authors/toshiki-hirao/_index.md
> +  link: #https://github.com/USERNAME
メールアドレス、及びtwitterのみ記載しました。

2021-08-08 01:45 UTC, toshiki-h commented on content/en/authors/toshiki-hirao/_index.md
> +  url: ""
Done

2021-08-08 01:50 UTC, toshiki-h commented on content/en/authors/toshiki-hirao/_index.md
> +    year: 2012
削除しました。今後、別途編集追加して、別のPRで挙げます。

2021-08-08 01:56 UTC, toshiki-h commented on content/en/authors/toshiki-hirao/_index.md
> +role:
done

2021-08-08 01:58 UTC, toshiki-h commented
@keichi 全て修正が完了しました。恐れ入りますが、ご確認のほど宜しくお願い申し上げます。

2021-08-08 02:13 UTC, keichi approved these changes
対応ありがとうございました！

2021-08-08 02:14 UTC, merged